### ISSUE TITLE
压缩合并以后的css如何调试？

### ISSUE THREAD

**Issue by chemzqm** [wangjeaf/CSSCheckStyle#3]
压缩合并前我们可以在浏览器中定位元素找到对应样式的行号，方便我们定位修正，进行压缩合并以后找到的行号文件名就失去意义了。

该工具目前有解决这个问题吗？没有的话或许可以参考stylus添加注释/firebug插件增强的方式。

**Comment by hax** [comment]
几种可能的方式：
1. 楼上说的方式
2. 直接加注释
3. 用代理服务器或类似技术替换为源文件
4. sourcemap

**Comment by wangjeaf** [comment]
这个还真不好弄，目前只能通过查看元素的selector，然后在压缩后的源码里去搜了。也可以参考楼上说的一些方法。
正常流程应该是，在合并压缩之前，先用fixstyle修复一遍，利用修复好的css进行调试和测试，提交之前自动ckstyle，测试通过发布时compress，最终上线。

**Comment by hustKiwi** [comment]
@wangjeaf 现在的compress会对结构做更改吧？比如https://github.com/wangjeaf/CSSCheckStyle/issues/2 提到的bug就是compress后出现的，那么这种情况fixstyle可以保证和compress后结果高度拟真么？或者考虑在compress之行是加上debug参数，只做结构合并等压缩优化，但不做去除空格和换行的操作，这样至少保证可以便于发现CSSCheckStyle本身的压缩问题。

**Comment by wangjeaf** [comment]
@hustKiwi 
哈哈，kiwi出现！
现在的fixstyle时已经对结构做了变更，compress只是在fixstyle之后，调用了每一个entity的fixed方法获取压缩后的数据。你所说的compress --debug，实际上就是fixstyle的工作了。

**Comment by wangjeaf** [comment]
@hustKiwi 
除了空格、缩进和注释外，fixstyle和compress的代码是完全一致的~

**Comment by wangjeaf** [comment]
@chemzqm 用fixstyle的代码进行调试吧，调试没有问题以后再compress就可以了。因为这两者生成的代码在功能上没有差别。实际上，compress会先fixstyle一下。
