### ISSUE TITLE
macos sublime插件问题.

### ISSUE THREAD

**Issue by zoono2022** [wangjeaf/CSSCheckStyle#8]
如果是macos用户, 可能安装sublime2 插件,无法直接使用.. 我自己遇到的情况大概和环境变量有关. 但奇怪之处在于,无论bin/bash 还是 bin/sh  我在终端里用 都是ok的...

我用笨办法解决的. 仅仅作为提醒吧,希望你能给出更简单的解决办法.
把sublime对应插件目录中
CkStylePlugin.py, FixStylePlugin.py  , FixStyleSafePlugin.py, FixStyleSingleLinePlugin.py,  CssCompressPlugin.py  里面的

cmd = 'ckstyle "' + path + '"'
改为
cmd = '/usr/local/bin/ckstyle "' + path + '"'

其中 /usr/local/bin/ 是 安装目录.
你可以 type  或 which csstyle  来得到该路径.

**Comment by wangjeaf** [comment]
如果有需要，我可以专门针对mac用户，在代码里加上/usr/local/bin/ckstyle是否存在的判断，先观望一下有多少同学会遇到这个问题吧。

多谢 frankqnj 同学的贡献！

**Comment by wangjeaf** [comment]
1.1.0版本中已经加入了路径检测，请更新试用吧~
