### ISSUE TITLE
希望更加细化rule的配置

### ISSUE THREAD

**Issue by jtyjty99999** [wangjeaf/CSSCheckStyle#9]
非常赞的东东！
目前rule还只有 包含跟忽略的配置，每个rule好像无法具体配置，都是一些py文件
因为看到插件开发了，所以想插件是不是可以直接配一个配置，之后用总入口来管理，就像gruntjs的配置一样。
比如FEDCanNotSetFontFamily. 可以设置字体白名单啊
FEDMultiLineSpaces 可以设置空格数量之类

还有就是prefix这个问题 建议在prefix检查中增加一个是否使用了prefix.js插件

另外强烈建议推出nodejs版本~

**Comment by wangjeaf** [comment]
多谢99的建议。

1、rule的具体配置，在ckstyle.ini中，如果专门加一个section叫做[plugins]，里面可以由开发者自行添加规则，然后将此配置信息放置到贯穿所有代码的config里，是不是可以满足要求了？ckstyle.ini请参见：https://github.com/wangjeaf/CSSCheckStyle#config-file-demo
2、prefix.js是个什么东东？为什么要在CSS检查过程中判断是否使用了一个js插件？还请明示。
3、nodejs版本要求很强烈哇，我一定尽快！你如果感兴趣也可以参与进来哟~

盼复。

**Comment by wangjeaf** [comment]
现已在ckstyle.ini中添加了plugin section，可用于配置插件的个性化信息，通过fix/check方法的config.pluginConfig即可获取。
例如：
[plugin]
plugin-class-a-config = 1

在插件类中，通过 config.pluginConfig.get('plugin-class-a-config')即可获取到了。
不知道有没有解决你说的问题1~~~

**Comment by jtyjty99999** [comment]
plugin的问题已经解决~非常佩服开发者的效率！
前缀是非常烦的一个东东，所以出了很多插件来解决 ，比如 
http://prefixr.com/index.php
http://leaverou.github.io/prefixfree/
还有另外一个场景是利用 http://modernizr.com/ 来书写support的css时，有一些特殊的css写法

**Comment by wangjeaf** [comment]
前缀的功能实际上添加一个plugin就能搞定，只是目前ckstyle暂不做任何对css功能有影响的操作，如果确实有需要，可以纳入考虑，并在现有ckstyle功能完备之后，作为一个可选plugin放置在官方插件库内 https://github.com/wangjeaf/ckstyle-pm ，并在新版ckstyle中一键安装（目前尚未正式开放哈）

**Comment by wangjeaf** [comment]
插件的安装将在即将推出的新版ckstyle中提供，敬请期待。

**Comment by jtyjty99999** [comment]
期待ing！
